"""The CyberAthlete domain core, on the server side — ADR-004 option B.

One implementation of the logic the phone and the server must agree on exactly, compiled from
`core-rs/` and reached through PyO3. Import it from `app.domain`, never from a service or a router:
the fence in `.importlinter` says so, and the reason is that a second caller is how a second
rounding rule eventually appears.

Everything here is pure (INV-10): no I/O, no clock, no randomness, and `now` is always a parameter.
"""

from ._core import (
    ENGINE_VERSION,
    CycleOneSet,
    ExerciseSpec,
    LoggedSet,
    MesocycleSpec,
    PersonalBests,
    PlannedExercise,
    PlannedMicrocycle,
    PlannedSession,
    PlannedSet,
    PrAchievement,
    PrKind,
    ProgressionRule,
    ProgressionStrategy,
    RepsAtWeight,
    RoundingMode,
    SessionMetrics,
    SessionSpec,
    SetEntry,
    SetType,
    StandingRecord,
    Tracking,
    core_version,
    counted_set_count,
    detect_prs,
    e1rm,
    e1rm_series,
    generate,
    is_counted_set,
    load_kg,
    missing_for_completion,
    personal_bests,
    resolve_dates,
    round_to_increment,
    session_metrics,
    standing_records,
    volume_kg,
)

__all__ = [
    "ENGINE_VERSION",
    "CycleOneSet",
    "ExerciseSpec",
    "LoggedSet",
    "MesocycleSpec",
    "PersonalBests",
    "PlannedExercise",
    "PlannedMicrocycle",
    "PlannedSession",
    "PlannedSet",
    "PrAchievement",
    "PrKind",
    "ProgressionRule",
    "ProgressionStrategy",
    "RepsAtWeight",
    "RoundingMode",
    "SessionMetrics",
    "SessionSpec",
    "SetEntry",
    "SetType",
    "StandingRecord",
    "Tracking",
    "core_version",
    "counted_set_count",
    "detect_prs",
    "e1rm",
    "e1rm_series",
    "generate",
    "is_counted_set",
    "load_kg",
    "missing_for_completion",
    "personal_bests",
    "resolve_dates",
    "round_to_increment",
    "session_metrics",
    "standing_records",
    "volume_kg",
]
