/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Deletion
         * @description Schedules the account's deletion for seven days on, and says when (task 019).
         */
        post: operations["request_deletion_api_v1_auth_deletion_post"];
        /** Cancel Deletion */
        delete: operations["cancel_deletion_api_v1_auth_deletion_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Email */
        post: operations["change_email_api_v1_auth_email_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_email_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_email_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Password Reset */
        post: operations["request_password_reset_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_api_v1_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exercises
         * @description The global catalog and the user's own exercises, by id, a page at a time.
         */
        get: operations["list_exercises_api_v1_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercise
         * @description A global or one of the user's own. Someone else's answers 404, like an absent one (04 §4).
         */
        get: operations["get_exercise_api_v1_exercises__exercise_id__get"];
        /**
         * Put Exercise
         * @description Creates or updates one of the user's own exercises (decision 3). The copy with the newer
         *     `updated_at` wins; a global's id, like somebody else's, is `409 id_unavailable`.
         */
        put: operations["put_exercise_api_v1_exercises__exercise_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Routines
         * @description The user's routines, without their exercises, by id, a page at a time.
         */
        get: operations["list_routines_api_v1_routines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Routine
         * @description The routine and every exercise entry, archived ones included. 404 for someone else's.
         */
        get: operations["get_routine_api_v1_routines__routine_id__get"];
        /**
         * Put Routine
         * @description Applies the document row by row — each row's newer `updated_at` wins, a row left out is
         *     kept — and answers with the routine as stored (decision 1). Idempotent: resending changes
         *     nothing.
         */
        put: operations["put_routine_api_v1_routines__routine_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workouts
         * @description The user's workouts, without their exercises, newest start first, a page at a time.
         */
        get: operations["list_workouts_api_v1_workouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workout
         * @description The workout, every exercise entry and every set, archived ones included. 404 for a workout
         *     that does not exist and for one that is somebody else's alike (04 §4).
         */
        get: operations["get_workout_api_v1_workouts__workout_id__get"];
        /**
         * Put Workout
         * @description Applies the document row by row — each row's newer `updated_at` wins, a row left out is
         *     kept — and answers with the workout as stored (decision 1). Idempotent by the client's ids
         *     (INV-16): resending changes nothing. A completed set without its mode's measure is
         *     `422 set_missing_<field>` (decision 2).
         */
        put: operations["put_workout_api_v1_workouts__workout_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description The process is alive. Says nothing about the database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Traffic may be sent: Postgres is reachable and its schema is not behind this build.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptedResponse
         * @description The same body whatever happened behind it — the reset request must not say whether an account
         *     exists.
         */
        AcceptedResponse: {
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
        };
        /** AccountResponse */
        AccountResponse: {
            /** Birth Date */
            birth_date: string | null;
            /** Deletion Requested At */
            deletion_requested_at: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Gamification Enabled */
            gamification_enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "en" | "pt-BR";
            /** Max Hr */
            max_hr: number | null;
            privacy_key: components["schemas"]["PrivacyKeyOut"] | null;
            /** Resting Hr */
            resting_hr: number | null;
            /** Sex */
            sex: ("male" | "female" | "unspecified") | null;
            /** Timezone */
            timezone: string;
            /**
             * Unit System
             * @enum {string}
             */
            unit_system: "metric" | "imperial";
        };
        /**
         * AccountUpdate
         * @description Only what a user edits by hand. Omitted fields stay as they are; the optional ones may be
         *     cleared.
         */
        AccountUpdate: {
            /** Birth Date */
            birth_date?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Gamification Enabled */
            gamification_enabled?: boolean | null;
            /** Locale */
            locale?: ("en" | "pt-BR") | null;
            /** Max Hr */
            max_hr?: number | null;
            /** Resting Hr */
            resting_hr?: number | null;
            /** Sex */
            sex?: ("male" | "female" | "unspecified") | null;
            /** Timezone */
            timezone?: string | null;
            /** Unit System */
            unit_system?: ("metric" | "imperial") | null;
        };
        /** DeletionRequest */
        DeletionRequest: {
            /** Password */
            password: string;
        };
        /**
         * DeletionResponse
         * @description When the deletion was asked for, and the moment from which the account is deleted.
         */
        DeletionResponse: {
            /**
             * Deleted From
             * Format: date-time
             */
            deleted_from: string;
            /**
             * Deletion Requested At
             * Format: date-time
             */
            deletion_requested_at: string;
        };
        /** EmailChangeRequest */
        EmailChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Email */
            new_email: string;
        };
        /** EmailVerifyRequest */
        EmailVerifyRequest: {
            /** Token */
            token: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            error: string;
        };
        /** ExercisePage */
        ExercisePage: {
            /** Items */
            items: components["schemas"]["ExerciseResponse"][];
            /** Next */
            next: string | null;
        };
        /**
         * ExerciseResponse
         * @description A global exercise carries a translation key and no name; the user's own carries a name and
         *     no key (INV-27). `is_own` says which.
         */
        ExerciseResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Max Reps */
            default_max_reps: number | null;
            /** Default Min Reps */
            default_min_reps: number | null;
            /** Deleted At */
            deleted_at: string | null;
            /** Forked From Id */
            forked_from_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Own */
            is_own: boolean;
            /** Is Unilateral */
            is_unilateral: boolean;
            /** Load Increment Kg */
            load_increment_kg: number | null;
            /**
             * Modality
             * @enum {string}
             */
            modality: "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "band" | "other";
            /** Name */
            name: string | null;
            /** Name Key */
            name_key: string | null;
            /** Notes */
            notes: string | null;
            /** Primary Muscle Id */
            primary_muscle_id: number;
            /** Secondary Muscle Ids */
            secondary_muscle_ids: number[];
            /**
             * Tracking
             * @enum {string}
             */
            tracking: "weight_reps" | "reps_only" | "duration" | "distance_duration";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Uses Bodyweight */
            uses_bodyweight: boolean;
        };
        /**
         * ExerciseWrite
         * @description One of the user's own exercises. The name is stored exactly as typed and never translated
         *     (INV-27); a fork names the exercise it came from (stage 4).
         */
        ExerciseWrite: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Max Reps */
            default_max_reps?: number | null;
            /** Default Min Reps */
            default_min_reps?: number | null;
            /** Deleted At */
            deleted_at?: string | null;
            /** Forked From Id */
            forked_from_id?: string | null;
            /**
             * Is Unilateral
             * @default false
             */
            is_unilateral: boolean;
            /** Load Increment Kg */
            load_increment_kg?: number | null;
            /**
             * Modality
             * @enum {string}
             */
            modality: "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "band" | "other";
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Primary Muscle Id */
            primary_muscle_id: number;
            /** Secondary Muscle Ids */
            secondary_muscle_ids?: number[];
            /**
             * Tracking
             * @default weight_reps
             * @enum {string}
             */
            tracking: "weight_reps" | "reps_only" | "duration" | "distance_duration";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Uses Bodyweight
             * @default false
             */
            uses_bodyweight: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LoginRequest */
        LoginRequest: {
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name?: string | null;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PasswordChangeRequest */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
            privacy_key: components["schemas"]["PrivacyKeyIn"];
        };
        /** PasswordResetConfirmRequest */
        PasswordResetConfirmRequest: {
            /** New Password */
            new_password: string;
            privacy_key: components["schemas"]["PrivacyKeyIn"];
            /** Token */
            token: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** Email */
            email: string;
        };
        /**
         * PrivacyKeyIn
         * @description The privacy key wrapped on the device — base64 — and the KDF it was wrapped under
         *     (ADR-007).
         */
        PrivacyKeyIn: {
            /** Kdf */
            kdf: string;
            /**
             * Salt
             * Format: base64
             */
            salt: string;
            /**
             * Wrapped Key
             * Format: base64
             */
            wrapped_key: string;
        };
        /** PrivacyKeyOut */
        PrivacyKeyOut: {
            /** Kdf */
            kdf: string;
            /** Salt */
            salt: string;
            /** Wrapped Key */
            wrapped_key: string;
        };
        /** ReadinessStatus */
        ReadinessStatus: {
            /** Reason */
            reason?: ("database_unreachable" | "migrations_pending") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name?: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "en" | "pt-BR";
            /** Password */
            password: string;
            privacy_key: components["schemas"]["PrivacyKeyIn"];
            /** Timezone */
            timezone: string;
            /**
             * Unit System
             * @enum {string}
             */
            unit_system: "metric" | "imperial";
        };
        /**
         * RoutineDocument
         * @description A routine and its exercises. An exercise left out is kept, not removed: archiving travels
         *     as its `deleted_at` (02 §7, INV-11).
         */
        RoutineDocument: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["RoutineExerciseDocument"][];
            /** Folder */
            folder?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RoutineExerciseDocument */
        RoutineExerciseDocument: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes?: string | null;
            /** Order Index */
            order_index: number;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Superset Group */
            superset_group?: number | null;
            /** Target Max Reps */
            target_max_reps?: number | null;
            /** Target Min Reps */
            target_min_reps?: number | null;
            /** Target Rir */
            target_rir?: number | null;
            /** Target Sets */
            target_sets?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RoutinePage */
        RoutinePage: {
            /** Items */
            items: components["schemas"]["RoutineSummary"][];
            /** Next */
            next: string | null;
        };
        /** RoutineResponse */
        RoutineResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["RoutineExerciseDocument"][];
            /** Folder */
            folder?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RoutineSummary
         * @description A routine in a list, without its exercises.
         */
        RoutineSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Folder */
            folder: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Order Index */
            order_index: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Current */
            current: boolean;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Active At
             * Format: date-time
             */
            last_active_at: string;
        };
        /** SetDocument */
        SetDocument: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Distance M */
            distance_m?: number | null;
            /** Duration S */
            duration_s?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Completed
             * @default false
             */
            is_completed: boolean;
            /** Planned Set Id */
            planned_set_id?: string | null;
            /** Reps */
            reps?: number | null;
            /** Rir */
            rir?: number | null;
            /** Set Index */
            set_index: number;
            /**
             * Set Type
             * @default working
             * @enum {string}
             */
            set_type: "warmup" | "working" | "drop" | "backoff" | "amrap";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** SignedInResponse */
        SignedInResponse: {
            /**
             * Access Expires At
             * Format: date-time
             */
            access_expires_at: string;
            /** Access Token */
            access_token: string;
            account: components["schemas"]["AccountResponse"];
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** TokensResponse */
        TokensResponse: {
            /**
             * Access Expires At
             * Format: date-time
             */
            access_expires_at: string;
            /** Access Token */
            access_token: string;
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkoutDocument
         * @description A workout, its exercise entries and their sets. A row left out is kept, not removed:
         *     archiving travels as its `deleted_at` (02 §7, INV-11). `local_date` and `tz` are the day and
         *     zone it was recorded in, stored as facts (INV-17).
         */
        WorkoutDocument: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["WorkoutExerciseDocument"][];
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Notes */
            notes?: string | null;
            /** Perceived Fatigue */
            perceived_fatigue?: number | null;
            /** Planned Session Id */
            planned_session_id?: string | null;
            /** Routine Id */
            routine_id?: string | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "plan" | "routine";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Title */
            title: string;
            /** Tz */
            tz: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkoutExerciseDocument */
        WorkoutExerciseDocument: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes?: string | null;
            /** Order Index */
            order_index: number;
            /** Planned Exercise Id */
            planned_exercise_id?: string | null;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Sets */
            sets?: components["schemas"]["SetDocument"][];
            /** Superset Group */
            superset_group?: number | null;
            /** Target Max Reps */
            target_max_reps?: number | null;
            /** Target Min Reps */
            target_min_reps?: number | null;
            /** Target Rir */
            target_rir?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkoutPage */
        WorkoutPage: {
            /** Items */
            items: components["schemas"]["WorkoutSummary"][];
            /** Next */
            next: string | null;
        };
        /** WorkoutResponse */
        WorkoutResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["WorkoutExerciseDocument"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Notes */
            notes?: string | null;
            /** Perceived Fatigue */
            perceived_fatigue?: number | null;
            /** Planned Session Id */
            planned_session_id?: string | null;
            /** Routine Id */
            routine_id?: string | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "plan" | "routine";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Title */
            title: string;
            /** Tz */
            tz: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WorkoutSummary
         * @description A workout in a list, without its exercises.
         */
        WorkoutSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Notes */
            notes: string | null;
            /** Perceived Fatigue */
            perceived_fatigue: number | null;
            /** Planned Session Id */
            planned_session_id: string | null;
            /** Routine Id */
            routine_id: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "plan" | "routine";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Title */
            title: string;
            /** Tz */
            tz: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_deletion_api_v1_auth_deletion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_deletion_api_v1_auth_deletion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_email_api_v1_auth_email_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_email_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_email_api_v1_auth_email_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedInResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    update_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedInResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sessions_api_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    revoke_session_api_v1_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_v1_exercises_get: {
        parameters: {
            query?: {
                after?: string | null;
                limit?: number;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_v1_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_exercise_api_v1_exercises__exercise_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_routines_api_v1_routines_get: {
        parameters: {
            query?: {
                after?: string | null;
                limit?: number;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutinePage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routine_api_v1_routines__routine_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_routine_api_v1_routines__routine_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_workouts_api_v1_workouts_get: {
        parameters: {
            query?: {
                before?: string | null;
                limit?: number;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_api_v1_workouts__workout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_workout_api_v1_workouts__workout_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
}
