#ifndef CYBERATHLETE_CORENATIVE_H
#define CYBERATHLETE_CORENATIVE_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace cyberathlete_corenative {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* CYBERATHLETE_CORENATIVE_H */