// Generated by uniffi-bindgen-react-native
#include "cyberathlete-core-native.h"
#include "generated/cyberathlete_core_ffi.hpp"

namespace cyberathlete_corenative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeCyberathleteCoreFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}