-- Task 004 stage 5c (03 §4): set_logs.distance_m becomes real, so 100 ft typed (30.48 m) reads back as 100 ft, not 98.
--
-- Generated by drizzle-kit and kept as generated — but read and proven first, as 06 §4 requires after 0002's
-- generated rebuild would have deleted every logged set. This rebuild is safe where that one was not: nothing on the
-- device references set_logs, so the DROP inside the migrator's single transaction (where the PRAGMA lines are no-ops)
-- cascades into nothing, and the copy selects only columns the old table has. Run against a copy of the stage 5 test
-- phone's own database: every set survived, foreign_key_check empty, integrity_check ok, both CHECKs still enforced
-- after the rename (SQLite rewrites the "__new_set_logs"-qualified reference), and both indexes recreated.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_set_logs` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`workout_exercise_id` text NOT NULL,
	`set_index` integer NOT NULL,
	`set_type` text DEFAULT 'working' NOT NULL,
	`weight_kg` real,
	`reps` integer,
	`rir` integer,
	`distance_m` real,
	`duration_s` integer,
	`is_completed` integer DEFAULT false NOT NULL,
	`completed_at` integer,
	`planned_set_id` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`sync_version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`workout_exercise_id`) REFERENCES `workout_exercises`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`planned_set_id`) REFERENCES `planned_sets`(`id`) ON UPDATE no action ON DELETE set null,
	CONSTRAINT "set_logs_set_type_check" CHECK("set_type" IN ('warmup', 'working', 'drop', 'backoff', 'amrap')),
	CONSTRAINT "set_logs_weight_kg_check" CHECK("__new_set_logs"."weight_kg" >= 0),
	CONSTRAINT "set_logs_reps_check" CHECK("reps" BETWEEN 0 AND 1000),
	CONSTRAINT "set_logs_rir_check" CHECK("rir" BETWEEN 0 AND 10)
);
--> statement-breakpoint
INSERT INTO `__new_set_logs`("id", "user_id", "workout_exercise_id", "set_index", "set_type", "weight_kg", "reps", "rir", "distance_m", "duration_s", "is_completed", "completed_at", "planned_set_id", "created_at", "updated_at", "deleted_at", "sync_version") SELECT "id", "user_id", "workout_exercise_id", "set_index", "set_type", "weight_kg", "reps", "rir", "distance_m", "duration_s", "is_completed", "completed_at", "planned_set_id", "created_at", "updated_at", "deleted_at", "sync_version" FROM `set_logs`;--> statement-breakpoint
DROP TABLE `set_logs`;--> statement-breakpoint
ALTER TABLE `__new_set_logs` RENAME TO `set_logs`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `set_logs_position` ON `set_logs` (`workout_exercise_id`,`set_index`);--> statement-breakpoint
CREATE INDEX `set_logs_planned_set_id_idx` ON `set_logs` (`planned_set_id`) WHERE "set_logs"."planned_set_id" IS NOT NULL;