/**
 * Plain HTTP is allowed in debug builds only, and only to this machine (04 §5).
 *
 * A debug build reaches the API at http://localhost:8000 over `adb reverse`. A release build permits no
 * cleartext at all. The rule lives in an Android network security config, which on every Android
 * version this app supports overrides `usesCleartextTraffic`:
 *
 *   - src/main/res/xml/network_security_config.xml   no cleartext, anywhere
 *   - src/debug/res/xml/network_security_config.xml  the debug variant's override: localhost only
 *
 * Android native configuration is generated by `expo prebuild` and never committed, so this plugin is
 * the source of truth. scripts/check-release-cleartext.mjs proves the release result in CI. Platform
 * configuration in a config plugin is the one place besides src/platform/ INV-28 allows it.
 */
const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const RESOURCE_NAME = 'network_security_config';

const RELEASE_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDebugOnlyLocalhostCleartext.js — edit the plugin, not this file. -->
<!-- Release: no cleartext traffic, to any host (04 §5). -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;

const DEBUG_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDebugOnlyLocalhostCleartext.js — edit the plugin, not this file. -->
<!-- Debug only: http to this machine over adb reverse, and to nothing else (04 §5). -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">127.0.0.1</domain>
    </domain-config>
</network-security-config>
`;

function withNetworkSecurityConfigFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const sourceSets = path.join(modConfig.modRequest.platformProjectRoot, 'app', 'src');
      for (const [sourceSet, contents] of [
        ['main', RELEASE_CONFIG],
        ['debug', DEBUG_CONFIG],
      ]) {
        const directory = path.join(sourceSets, sourceSet, 'res', 'xml');
        await fs.promises.mkdir(directory, { recursive: true });
        await fs.promises.writeFile(path.join(directory, `${RESOURCE_NAME}.xml`), contents);
      }
      return modConfig;
    },
  ]);
}

function withNetworkSecurityConfigReference(config) {
  return withAndroidManifest(config, (modConfig) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(modConfig.modResults);
    application.$['android:networkSecurityConfig'] = `@xml/${RESOURCE_NAME}`;
    return modConfig;
  });
}

module.exports = function withDebugOnlyLocalhostCleartext(config) {
  return withNetworkSecurityConfigReference(withNetworkSecurityConfigFiles(config));
};
