// Generated by scripts/render-brand-assets.mjs from assets/brand/*.svg. Do not edit: change the SVG, then run
// `pnpm render:brand`.

export type MarkLevel = 'full' | 'reduced' | 'silhouette' | 'glyph';

/** Each level of the mark as SVG drawn in `currentColor` (07 §1). */
export const MARKS: Readonly<Record<MarkLevel, string>> = {
  full: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" fill="none" stroke="currentColor" stroke-width="3"/><line x1="10" y1="10" x2="90" y2="90" stroke="currentColor" stroke-width="3"/><line x1="90" y1="10" x2="10" y2="90" stroke="currentColor" stroke-width="3"/></svg>',
  reduced: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" fill="none" stroke="currentColor" stroke-width="4"/><line x1="10" y1="10" x2="90" y2="90" stroke="currentColor" stroke-width="4"/><line x1="90" y1="10" x2="10" y2="90" stroke="currentColor" stroke-width="4"/></svg>',
  silhouette: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" fill="none" stroke="currentColor" stroke-width="6"/><line x1="10" y1="10" x2="90" y2="90" stroke="currentColor" stroke-width="6"/><line x1="90" y1="10" x2="10" y2="90" stroke="currentColor" stroke-width="6"/></svg>',
  glyph: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="12" y="12" width="76" height="76" fill="none" stroke="currentColor" stroke-width="10"/><line x1="12" y1="12" x2="88" y2="88" stroke="currentColor" stroke-width="10"/><line x1="88" y1="12" x2="12" y2="88" stroke="currentColor" stroke-width="10"/></svg>',
};

/** The levels still holding task 011's placeholder. Task 018 is done when this is empty. */
export const PLACEHOLDER_LEVELS: readonly MarkLevel[] = ['full', 'reduced', 'silhouette', 'glyph'];
